-- Fleet-wide Cowork v2 rollout health and automatic rollback.
--
-- Every v2 terminal outcome is recorded through one serialized RPC. The RPC
-- recomputes the latest 200-turn window and latches rollback open at 1% hard
-- failures. Application routing reads the singleton before selecting v2 and
-- fails closed to the hardened baseline when the state cannot be read.

begin;

create table if not exists public.cowork_rollout_health_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  route text not null check (
    route in ('direct_writer', 'read_only_orchestrator', 'action_orchestrator')
  ),
  terminal_outcome text not null check (
    terminal_outcome in (
      'delivered',
      'clarified',
      'cancelled',
      'recoverable_error',
      'hard_failure'
    )
  )
);

create index if not exists cowork_rollout_health_events_latest_idx
  on public.cowork_rollout_health_events (id desc);

create table if not exists public.cowork_rollout_health (
  singleton boolean primary key default true check (singleton),
  sample_size integer not null default 0 check (sample_size between 0 and 200),
  hard_failures integer not null default 0 check (
    hard_failures between 0 and sample_size
  ),
  hard_failure_rate numeric not null default 0 check (
    hard_failure_rate between 0 and 1
  ),
  state text not null default 'insufficient' check (
    state in ('insufficient', 'healthy', 'alert', 'rollback')
  ),
  rollback_open boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.cowork_rollout_health (singleton)
values (true)
on conflict (singleton) do nothing;

create or replace function public.record_cowork_rollout_health(
  p_route text,
  p_terminal_outcome text
)
returns public.cowork_rollout_health
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sample_size integer;
  v_hard_failures integer;
  v_hard_failure_rate numeric;
  v_state text;
  v_result public.cowork_rollout_health;
begin
  if p_route not in (
    'direct_writer',
    'read_only_orchestrator',
    'action_orchestrator'
  ) then
    raise exception 'invalid Cowork rollout route';
  end if;
  if p_terminal_outcome not in (
    'delivered',
    'clarified',
    'cancelled',
    'recoverable_error',
    'hard_failure'
  ) then
    raise exception 'invalid Cowork terminal outcome';
  end if;

  -- Serialize window maintenance so concurrent serverless instances cannot
  -- overwrite a newer aggregate with a stale one.
  perform pg_advisory_xact_lock(hashtext('cowork_rollout_health_v2'));

  insert into public.cowork_rollout_health_events (route, terminal_outcome)
  values (p_route, p_terminal_outcome);

  with latest as (
    select terminal_outcome
    from public.cowork_rollout_health_events
    order by id desc
    limit 200
  )
  select
    count(*)::integer,
    count(*) filter (where terminal_outcome = 'hard_failure')::integer
  into v_sample_size, v_hard_failures
  from latest;

  v_hard_failure_rate := case
    when v_sample_size = 0 then 0
    else v_hard_failures::numeric / v_sample_size::numeric
  end;
  v_state := case
    when v_sample_size < 200 then 'insufficient'
    when v_hard_failure_rate >= 0.01 then 'rollback'
    when v_hard_failure_rate >= 0.005 then 'alert'
    else 'healthy'
  end;

  update public.cowork_rollout_health
  set sample_size = v_sample_size,
      hard_failures = v_hard_failures,
      hard_failure_rate = v_hard_failure_rate,
      state = case
        when rollback_open then 'rollback'
        else v_state
      end,
      rollback_open = rollback_open or v_state = 'rollback',
      updated_at = now()
  where singleton
  returning * into v_result;

  -- Bound operational storage while retaining much more than the active
  -- decision window for incident review.
  delete from public.cowork_rollout_health_events
  where id < coalesce(
    (
      select min(kept.id)
      from (
        select id
        from public.cowork_rollout_health_events
        order by id desc
        limit 10000
      ) as kept
    ),
    0
  );

  return v_result;
end;
$$;

alter table public.cowork_rollout_health_events enable row level security;
alter table public.cowork_rollout_health enable row level security;

-- Operational rollout evidence is service-only. No user-facing RLS policy is
-- intentionally created; the service role bypasses RLS.
revoke all on table public.cowork_rollout_health_events
  from public, anon, authenticated;
revoke all on table public.cowork_rollout_health
  from public, anon, authenticated;
revoke all on function public.record_cowork_rollout_health(text, text)
  from public, anon, authenticated;
grant select on table public.cowork_rollout_health to service_role;
grant execute on function public.record_cowork_rollout_health(text, text)
  to service_role;

insert into public.app_schema_version (singleton, version, updated_at)
values (true, 96, now())
on conflict (singleton) do update
set version = excluded.version, updated_at = excluded.updated_at;

commit;
